# Generated by Django 3.1.7 on 2021-03-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('rank', models.IntegerField()),
                ('date', models.DateField()),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsCycleApp.medium')),
            ],
        ),
    ]
